# video-crop-Sample
data:
    name: "IEMOCAP"
    root: "/sdb/visitors2/SCW/data/IEMOCAP/"
    para:
        name: "crop-10s"
        mode: "video"
        videomode: "crop"
        cascPATH: "/home/visitors2/SCW/torchTraining/utils/haarcascade_frontalface_alt2.xml"
        threads: 8
    enhances:
    transforms:       
        video:
            KeyFrameGetterBasedIntervalSampling:
                interval: 3
            Permute_Channel:
                dims: [0,1,2,3] # [seq,w,h,c]
    filters: {
        "replace": {'label':{"excited":"happy"}},
        "dropna": {'label': [ "other", "xxx", "excited" , "frustrated", "disgusted", "fearful", "surprised"] },
        "sort_values": "duration"
        }
