# video-crop-Sample
data:
    name: "IEMOCAP"
    root: "/sdb/user4/SCW/data/IEMOCAP/Feature/IEMOCAP-7s-audio_Wave_pad_cut_MFCC_Permute_Channel-.npy"
    para:
        name: ""
        mode: "audio"
        videomode: "crop"
        cascPATH: "/home/user4/SCW/torchTraining/utils/haarcascade_frontalface_alt2.xml"
        threads: 8
    enhances:
    transforms:
    filters: {
        "replace": {'label':{"excited":"happy"}},
        "dropna": {'label': [ "other", "xxx", "excited" , "frustrated", "disgusted", "fearful", "surprised"] },
        "sort_values": "duration"
        }
