# video-crop-Sample
data:
    name: "IEMOCAP"
    # IEMOCAP-7s-audio_Wave_pad_cut_MFCC_Permute_Channel-.npy, IEMOCAP-7s-audio_AudioSplit-audio_MFCC_Permute_Channel-.npy
    # IEMOCAP-3s-audio_Wave_pad_cut_MFCC_Permute_Channel-.npy, IEMOCAP-3s-audio_AudioSplit-audio_MFCC_Permute_Channel-.npy
    # IEMOCAP-10s-audio_Wave_pad_cut_MFCC_Permute_Channel-.npy
    # IEMOCAP-pad-audio_MFCC_Permute_Channel.npy
    root: "/sdb/visitors2/SCW/data/IEMOCAP/Feature/IEMOCAP-10s-audio_Wave_pad_cut_MFCC_Permute_Channel-.npy"
    para:
        name: ""
        mode: "audio"
        videomode: "crop"
        cascPATH: "/home/visitors2/SCW/torchTraining/utils/haarcascade_frontalface_alt2.xml"
        threads: 8
    enhances:
    transforms:
        audio: 
            MFCC:
                sample_rate: 16000
                n_mfcc: 40
                log_mels: True
                melkwargs:
                    n_fft: 1024
                    win_length: 1024
                    hop_length: 256
                    f_min: 80.
                    f_max: 7600.
                    pad: 0
                    n_mels: 128
                    power: 2.
                    normalized: True
                    center:  True
                    pad_mode: "reflect"
                    onesided: True
            Permute_Channel:
                dims: [2,1,0] # [c,seq.fea] - > [seq,fea,c]
    filters: {
        "replace": {'label':{"excited":"happy"}},
        "dropna": {'label': [ "other", "xxx", "excited" , "frustrated", "disgusted", "fearful", "surprised"] },
        "sort_values": "duration"
        }
