architecture:
    net: 
        name: "AudioNet" # VideoNet_Conv2D, AudioNet
        para: 
            num_class: 4
            model_name: "lightsernet" # 'resnet50', "lightsernet"
            last_hidden_dim: 320

architecture:
    net: 
        name: "AudioSVCNet" # AudioSVCNet_Step, AudioSVCNet, AudioSVCNet_Step_MultiObject, VideoSVCNet_Conv2D, VideoSVCNet_Step_Conv2D
        para:
            num_classes: 4
            model_name: "lightsernet"
            last_hidden_dim: 320
            seq_len: 189 # af_: 63*3 | vf_: 10*3
architecture:
    net: 
        name: "AudioSVNet" # AudioSVNet_Step, AudioSVNet, AudioSVNet_Step_MultiObject, VideoSVNet_Conv2D, VideoSVNet_Step_Conv2D
        para: 
            num_classes: 4
            model_name: "lightsernet"
            last_hidden_dim: 320
            seq_len: 189 # af_: 63*3 | vf_: 10*3
            emo_rnn_hidden_dim: 64
architecture:
    net: 
        name: "MIFFNet_Conv2D"
        para: 
            num_classes: 4
            model_name: ["lightsernet","resnet50"]
            last_hidden_dim: [320,320]
            seq_len: [189,30] # af_: 63*3 | vf_: 10*3
            emo_rnn_hidden_dim: [64,64]
