# 'resnet50', "lightsernet", 'densenet121',
# "vgg13", "aacnn", "glamnet", "macnn"

# architecture:
#     net:
#         name: "VideoNet_Conv2D" # VideoNet_Conv2D, AudioNet
#         para:
#             num_classes: 4
#             # 'resnet50',  'densenet121', "vgg13"
#             # "lightsernet", lightmultisernet, lightresmultisernet
#             model_name: "resnet50"
#             last_hidden_dim: 320
# architecture:
#     net:
#         name: "MViT" #
#         para:

# architecture:
#     net:
#         name: "AudioSVCNet_Step" # AudioSVCNet_Step, AudioSVCNet, AudioSVCNet_Step_MultiObject, VideoSVCNet_Conv2D, VideoSVCNet_Step_Conv2D
#         para:
#             num_classes: 4
#             model_name: "lightsernet" # 'resnet50', "lightsernet", 'densenet121',
#             last_hidden_dim: 320
#             seq_len: 189 # af_: 63*3=189|63*7=441 | vf_: 10*3
#             seq_step: 63

# architecture:
#     net:
#         name: "Audio_GloballyGatedMLP_SVC_BoxCox_Net"
#         para:
#             num_classes: 4
#             last_hidden_dim: 320
#             seq_len: 189 # af_: 63*3=189|63*7=441 | vf_: 10*3
#             seq_step: 63

# architecture:
#     net:
#         name: "CLANet"
#         para:
#             af_seq_len: 189
# architecture:
#     net:
#         name: "AudioSVNet_Step" # AudioSVNet_Step, AudioSVNet, AudioSVNet_Step_MultiObject, VideoSVNet_Conv2D, VideoSVNet_Step_Conv2D
#         para:
#             num_classes: 4
#             model_name: "lightsernet"
#             last_hidden_dim: 320
#             seq_len: 189 # af_: 63*3=189|63*7=441 | vf_: 10*3
#             emo_rnn_hidden_dim: 64

architecture:
    net:
        name: "MER_SISF_Conv2D_SVC_InterFusion_Joint_Attention_SLoss" # MIFFNet_Conv2D_InterFusion_Joint, MIFFNet_Conv2D_SVC_InterFusion_Joint
        para:
            num_classes: 4
            input_size: [[189, 40], [150, 150]]
            model_name: ["lightresmultisernet", "resnet50"] # "resnet50" "resmulti"
            last_hidden_dim: [320, 320]
            seq_len: [189, 30] # af_: 63*3=189, 63*7=441 | vf_: 10*3, 10*3
            enable_classifier: true
            # emo_rnn_hidden_dim: [64, 64]
# architecture:
#     net:
#         name: "InternImage"
#         para:
#             core_op: 'DCNv3'
#             channels: 80
#             depths: [4, 4, 21, 4]
#             groups: [5, 10, 20, 40]
#             num_classes: 4
#             drop_rate: 0.4
#             layer_scale: 0.00001
#             post_norm: True

# architecture:
#     net:
#         name: "DCRNet"
#         para:
#             with_dcn: True

# architecture:
#     net:
#         name: "CooperationNet"
#         para:
#             num_classes: [4, 4]
#             model_names: ["lightsernet", "lightresmultisernet"]
#             seq_len: [189, 189]
#             input_size: [[189, 40], [189, 40]]
#             last_hidden_dim: [320, 320]
#             seq_step: [189, 189]
