train:
    # 训练基础设置
    name: "AudioSVCNet_Step_MultiObject_noClassWeights_hanming_pc_10[7]s_CustomScheduler_step1s" # 本次运行模型名称
    nodes: 1 # 本次训练总共要使用的节点数量, 如果需要多台计算机进行分布式计算才需要设置
    node_rank: 1 # 当前节点在所有节点中的排名
    master_addr: '127.0.0.1' # 声明主进程 0 的 IP 地址和通信端口, 以便所有进程可以同步更新参数.
    master_port: '8888'
    USE_GPU: "0" # 设置当前节点(计算机)可用的 GPU 数量和顺序, 如果含有多个 GPU 将自动使用多 GPU 分布计算模式
    num_workers: 0 # 数据加载进程数
    seed: 42 # 设置随机数种子, 当设置了固定的随机数种子,之后依次生成的随机数序列也会被固定下来。
    train_rate: 0.8
    batch_size: 32 # 数据块大小
    n_epochs: 889 # 训练迭代次数
    Kfold: 0 # 
    # 预训练设置
    last_epochs: -1 # 恢复迭代的起始步
    checkpoint: False # "./checkpoints/Test model/000010.ckpt"
    # 分类
    loss_weight: True # 设置损失加权系数

sorlver:
    name: "Audio_Classification2MultiObject_MGDA_UB" # Audio_Classification, Video_Classification, Audio_Video_Classification, Audio_Video_Fusion_Classification,Audio_Classification2MultiObject_MGDA_UB
    optimizer: 
        name: "AdamW"
        lr: 0.0001 # 学习率
        para:
            betas: [0.9, 0.999]
    lr_method: 
        # name: "CosineAnnealingWarmRestarts"
        # mode: "step"
        # para:
        #     T_0: 1
        #     T_mult: 1
        #     eta_min: 0

        # name: "StepLR"
        # mode: "epoch"
        # para:
        #     step_size : 10
        #     gamma: 0.1

        name: "CustomScheduler"
        mode: "step"
        para: # epoch = (32*100000)/batchsize/batchlen  decay = 3196800
            epoch : 889
            batchlen: 450
            decay: 3196800
    loss_weights: True
logs: # 记录参数

    use_tensorboard: True # 记录展示
    log_dir: '/sdb/visitors2/SCW/logs/' # 记录存储文件夹
    log_every: 1 # 每几次 step进行记录
    model_save_dir: '/sdb/visitors2/SCW/checkpoint/' # 模型存放地址
    test_every: 1 # 每几次 epoch 进行测试
    model_save_every: 1 # 每几次 epoch 进行模型保存
    test_accuracy_every: 20 # 计算多少 epoch 的平均测试准确率
    verbose:
        config: True
        model: True
    SMTP:
        mail_host: "smtp.163.com"
        mail_port: "465"
        mail_user: "scharvin@163.com"
        mail_pass: "MXCFABEYKHITANVN"
    from_mail: "from@trainserver.com"
    to_mail: "1911523105@qq.com"